//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWarehouseWcfService.Models
{
    using System;

    public class Product
    {
        public int ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Barcode { get; set; }
        public string Description { get; set; }
        public Nullable<byte> VatPercent { get; set; }
        public Nullable<int> CreatedId { get; set; }
        public Nullable<DateTime> CreatedDate { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}