//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderDetailId { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<byte> VatPercent { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<short> InOrOut { get; set; }
        public Nullable<int> VariantId { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> CurrencyId { get; set; }
    }
}
