//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariantWithGroupName
    {
        public int VariantId { get; set; }
        public string Barcode { get; set; }
        public string P1Name { get; set; }
        public Nullable<int> P1Id { get; set; }
        public Nullable<int> P1GroupId { get; set; }
        public Nullable<int> P2Id { get; set; }
        public Nullable<int> P2GroupId { get; set; }
        public string P2Name { get; set; }
        public Nullable<int> P3Id { get; set; }
        public Nullable<int> P3GroupId { get; set; }
        public string P3Name { get; set; }
        public Nullable<int> P4Id { get; set; }
        public Nullable<int> P4GroupId { get; set; }
        public string P4Name { get; set; }
        public Nullable<int> P5Id { get; set; }
        public Nullable<int> P5GroupId { get; set; }
        public string P5Name { get; set; }
        public string P1GroupName { get; set; }
        public string P2GroupName { get; set; }
        public string P3GroupName { get; set; }
        public string P4GroupName { get; set; }
        public string P5GroupName { get; set; }
        public Nullable<int> ProductId { get; set; }
    }
}
