//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variant
    {
        public int VariantId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> PropertyId1 { get; set; }
        public Nullable<int> PropertyId2 { get; set; }
        public Nullable<int> PropertyId3 { get; set; }
        public Nullable<int> PropertyId4 { get; set; }
        public Nullable<int> PropertyId5 { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> CreatedId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
