//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwProductDetails
    {
        public int ProductDetailId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string DocumentCode { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<byte> VatPercent { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<int> CreatedId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> InOrOut { get; set; }
        public Nullable<int> VariantId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string WarehouseName { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Barcode { get; set; }
        public string CustomerCode { get; set; }
        public string CompanyName { get; set; }
        public string CustomerName { get; set; }
        public string CustomerSurname { get; set; }
        public string UnitName { get; set; }
    }
}
