//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwSupplier
    {
        public int SupplierId { get; set; }
        public string SupplierCode { get; set; }
        public string CompanyName { get; set; }
        public string SupplierName { get; set; }
        public string SupplierSurname { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Mail { get; set; }
        public string TaxNumber { get; set; }
        public string TaxOffice { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> TownId { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> CreatedId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> DefaultCurrencyId { get; set; }
        public string CountryName { get; set; }
        public string TownName { get; set; }
        public string CityName { get; set; }
        public string RegionName { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyCode { get; set; }
    }
}
