//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWarehouseWindows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderType
    {
        public int OrderTypeId { get; set; }
        public string OrderTypeName { get; set; }
        public string Description { get; set; }

        public override string ToString()
        {
            return OrderTypeName;
        }
    }
}
