//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWarehouseWindows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPriceList
    {
        public int ProductPriceListId { get; set; }
        public int ProductId { get; set; }
        public int PriceListGroupId { get; set; }
        public decimal Price { get; set; }
        public int CurrencyId { get; set; }
        public bool IsDefaultPrice { get; set; }
    }
}
