//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWarehouseWindows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail:ICloneable
    {
        public int ProductDetailId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string DocumentCode { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<byte> VatPercent { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<int> CreatedId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> InOrOut { get; set; }
        public Nullable<int> VariantId { get; set; }
        public bool IsApproved { get; set; }

        public string IsApprovedText
        {
            get => IsApproved ? "Onaylandý" : "-";
        }
        public string InOrOutText
        {
            get => InOrOut == -1 ? "Çýkýþ" : "Giriþ";
        }
        public object Clone()
        {
            return this.MemberwiseClone();
        }
    }
}
