//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace SimpleWarehouseWindows.Models
{
    using System;
    using System.Collections.Generic;
    [Description("Stok Birimi")]
    public partial class Unit
    {
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public string Description { get; set; }

        public override string ToString()
        {
            return UnitName;
        }
    }
}
