//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace SimpleWarehouseWindows.Models
{
    using System;
    using System.Collections.Generic;
    [Description("Varyant Grup")]
    public partial class VariantGroup
    {
        public int VariantGroupId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}
