//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWarehouseWindows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwOrder:Order
    {

        public bool IsDeleted { get; set; }
        public string OrderStatusName { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyCode { get; set; }
        public string OrderTypeName { get; set; }
       
        public string InvoiceCountryName { get; set; }
        public string InvoiceCityName { get; set; }
        public string InvoiceTownName { get; set; }
        public string DeliveryCountryName { get; set; }
        public string DeliveryCityName { get; set; }
        public string DeliveryTownName { get; set; }
        public string CustomerTitle
        {
            get { return this.CompanyName.Length > 0 ? this.CompanyName : ($"{CustomerName} {CustomerSurname}"); }
        }
    }
}
