//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWarehouseWindows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwProduct:Product
    {
        //public int ProductId { get; set; }
        //public string ProductCode { get; set; }
        //public string ProductName { get; set; }
        //public string Barcode { get; set; }
        //public string Description { get; set; }
        //public Nullable<byte> VatPercent { get; set; }
        //public Nullable<int> UnitId { get; set; }
        //public Nullable<int> CreatedId { get; set; }
        //public Nullable<System.DateTime> CreatedDate { get; set; }
        //public bool IsDeleted { get; set; }
        //public string UnitName { get; set; }
        public string UnitName { get; set; }
    }
}
