//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWarehouseWindows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwProductStockInWarehouse
    {
        public Nullable<int> ProductId { get; set; }
        public string ProductCode { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public string WarehouseName { get; set; }
        public string UnitName { get; set; }
    }
}
