//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWarehouseMobil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prefix
    {
        public int PrefixId { get; set; }
        public string PrefixName { get; set; }
        public string PrefixCode { get; set; }
        public int PrefixLength { get; set; }
        public int CurrentValue { get; set; }
    }
}
