//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWarehouseMobil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Town
    {
        public int TownId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Name { get; set; }
    }
}
