//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWarehouseMobil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwOrderDetails: OrderDetail
    {

        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Barcode { get; set; }
        public string CustomerCode { get; set; }
        public string CompanyName { get; set; }
        public string CustomerName { get; set; }
        public string CustomerSurname { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyCode { get; set; }
        public string UnitName { get; set; }
        public string VariantBarcode { get; set; }
        public string WarehouseName { get; set; }
        public string VariantName { get; set; }
    }
}
