//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWarehouseMobil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwProductPriceList
    {
        public string CurrencyName { get; set; }
        public string CurrencyCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Barcode { get; set; }
        public string GroupName { get; set; }
        public int ProductPriceListId { get; set; }
        public int ProductId { get; set; }
        public int PriceListGroupId { get; set; }
        public decimal Price { get; set; }
        public int CurrencyId { get; set; }
        public bool IsDefaultPrice { get; set; }
        public Nullable<int> GroupType { get; set; }
    }
}
